In [4]:
import pandas as pd

In [10]:
from google.colab import files
uploaded = files.upload()

Saving premier_league_complete_stats_until31thGameDayOnSeason2025-26.csv to premier_league_complete_stats_until31thGameDayOnSeason2025-26.csv

In [11]:
from google.colab import files
uploaded = files.upload()

Saving premier_league_complete_stats_until35thGameDayOnSeason2025-26.csv to premier_league_complete_stats_until35thGameDayOnSeason2025-26.csv

In [13]:
import pandas as pd

arsenal = pd.read_csv(
    "premier_league_complete_stats_until31thGameDayOnSeason2025-26.csv",
    encoding="latin1"
)

In [14]:
arsenal.head()

,player_name,team_name,position,accurateCrosses,accurateCrossesPercentage,accurateFinalThirdPasses,accurateLongBalls,accurateLongBallsPercentage,accurateOppositionHalfPasses,accurateOwnHalfPasses,...,totalDuelsWonPercentage,totalLongBalls,totalOppositionHalfPasses,totalOwnHalfPasses,totalPasses,totalShots,totwAppearances,touches,wasFouled,yellowCards
0,Declan Rice,Arsenal,M,41,28.082192,459,72,48.648649,891,687,...,61.111111,148,1054,743,1797,36,3,2327,8,2
1,Gabriel Magalhães,Arsenal,D,1,20.000000,180,63,46.323529,512,747,...,70.334928,136,622,797,1419,18,5,1747,27,3
2,Bukayo Saka,Arsenal,F,36,32.432432,300,14,36.842105,419,105,...,53.020134,38,557,126,683,63,4,1236,51,1
3,Martín Zubimendi,Arsenal,M,2,18.181818,369,48,49.484536,833,661,...,60.189573,97,985,709,1694,26,2,2026,10,4
4,Max Dowman,Arsenal,M,0,0.000000,9,0,0.000000,13,3,...,42.857143,0,14,3,17,5,0,51,4,0

In [15]:
epl = pd.read_csv(
    "premier_league_complete_stats_until35thGameDayOnSeason2025-26.csv",
    encoding="latin1"
)

In [16]:
epl.head()

,player_name,team_name,position,accurateChippedPasses,accurateCrosses,accurateCrossesPercentage,accurateFinalThirdPasses,accurateLongBalls,accurateLongBallsPercentage,accurateOppositionHalfPasses,...,totalLongBalls,totalOppositionHalfPasses,totalOwnHalfPasses,totalPasses,totalShots,totwAppearances,touches,wasFouled,yellowCards,yellowRedCards
0,Declan Rice,Arsenal,M,64,45,27.108434,501,81,49.090909,982,...,165,1166,832,1998,40,3,2591,9,3,0
1,Gabriel MagalhÃ£es,Arsenal,D,41,1,20.000000,196,73,45.341615,555,...,161,684,919,1603,24,5,1994,30,4,0
2,Bukayo Saka,Arsenal,F,15,37,32.173913,314,14,35.897436,441,...,39,583,135,718,66,5,1287,51,1,0
3,MartÃ­n Zubimendi,Arsenal,M,48,2,18.181818,391,51,47.663551,881,...,107,1049,774,1823,27,2,2206,13,4,0
4,William Saliba,Arsenal,D,26,4,44.444444,245,55,50.000000,651,...,110,747,1214,1961,5,0,2243,15,1,0

In [17]:
epl.columns

Index(['player_name', 'team_name', 'position', 'accurateChippedPasses',
       'accurateCrosses', 'accurateCrossesPercentage',
       'accurateFinalThirdPasses', 'accurateLongBalls',
       'accurateLongBallsPercentage', 'accurateOppositionHalfPasses',
       ...
       'totalLongBalls', 'totalOppositionHalfPasses', 'totalOwnHalfPasses',
       'totalPasses', 'totalShots', 'totwAppearances', 'touches', 'wasFouled',
       'yellowCards', 'yellowRedCards'],
      dtype='object', length=106)

In [18]:
arsenal.select_dtypes(include='number').shape

(517, 96)

In [19]:
arsenal.describe()

,accurateCrosses,accurateCrossesPercentage,accurateFinalThirdPasses,accurateLongBalls,accurateLongBallsPercentage,accurateOppositionHalfPasses,accurateOwnHalfPasses,accuratePasses,accuratePassesPercentage,aerialDuelsWon,...,totalDuelsWonPercentage,totalLongBalls,totalOppositionHalfPasses,totalOwnHalfPasses,totalPasses,totalShots,totwAppearances,touches,wasFouled,yellowCards
count,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,...,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000
mean,5.019342,16.213135,105.148936,24.988395,41.176116,212.686654,218.822050,431.508704,79.432921,19.642166,...,49.465233,59.729207,281.338491,242.243714,523.582205,14.798839,0.659574,755.143133,12.396518,2.232108
std,8.229250,17.318549,102.643656,35.832349,22.091051,199.448665,238.987608,404.773138,12.590400,23.777832,...,18.013153,97.278431,240.232243,255.340536,465.233691,16.505172,1.110281,609.141061,12.355185,2.301898
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,0.000000,0.000000,25.000000,3.000000,31.212724,51.000000,38.000000,101.000000,75.362319,4.000000,...,41.379310,6.000000,75.000000,46.000000,130.000000,2.000000,0.000000,216.000000,2.000000,0.000000
50%,1.000000,15.384615,79.000000,12.000000,42.857143,164.000000,141.000000,333.000000,81.954887,11.000000,...,49.756098,27.000000,241.000000,157.000000,415.000000,10.000000,0.000000,645.000000,9.000000,2.000000
75%,7.000000,26.666667,149.000000,32.000000,53.846154,310.000000,331.000000,640.000000,86.838535,25.000000,...,57.377049,69.000000,416.000000,369.000000,760.000000,21.000000,1.000000,1141.000000,19.000000,4.000000
max,53.000000,100.000000,567.000000,301.000000,100.000000,1000.000000,1498.000000,2086.000000,100.000000,147.000000,...,100.000000,740.000000,1204.000000,1564.000000,2340.000000,102.000000,6.000000,2780.000000,68.000000,10.000000

In [20]:
arsenal.sort_values("totalPasses", ascending=False).head(10)

,player_name,team_name,position,accurateCrosses,accurateCrossesPercentage,accurateFinalThirdPasses,accurateLongBalls,accurateLongBallsPercentage,accurateOppositionHalfPasses,accurateOwnHalfPasses,...,totalDuelsWonPercentage,totalLongBalls,totalOppositionHalfPasses,totalOwnHalfPasses,totalPasses,totalShots,totwAppearances,touches,wasFouled,yellowCards
106,Virgil van Dijk,Liverpool,D,0,0.000000,372,126,49.606299,1000,1086,...,75.409836,254,1204,1136,2340,22,3,2732,15,4
223,Lewis Dunk,Brighton &amp; Hove Albion,D,1,20.000000,164,75,48.387097,544,1498,...,58.854167,155,652,1564,2216,19,1,2552,8,10
133,Trevoh Chalobah,Chelsea,D,1,20.000000,169,48,41.739130,571,1396,...,57.142857,115,658,1451,2109,14,3,2486,18,3
199,Joachim Andersen,Fulham,D,4,28.571429,196,149,46.273292,565,1174,...,60.846561,322,768,1243,2011,12,3,2430,10,7
376,Elliot Anderson,Nottingham Forest,M,43,27.388535,504,106,56.684492,947,770,...,55.337691,187,1159,843,2002,36,2,2780,68,6
220,Jan Paul van Hecke,Brighton &amp; Hove Albion,D,9,47.368421,260,107,48.198198,666,1066,...,60.820896,222,864,1123,1987,19,5,2404,34,7
300,Marcos Senesi,Bournemouth,D,7,30.434783,264,153,39.130435,607,829,...,52.559727,391,925,928,1853,16,3,2418,28,8
81,Ezri Konsa,Aston Villa,D,1,20.000000,166,51,57.303371,593,1147,...,65.648855,89,650,1179,1829,11,0,2134,32,0
107,Dominik Szoboszlai,Liverpool,M,53,32.515337,567,108,59.668508,962,622,...,49.771690,181,1114,699,1813,58,4,2477,26,7
0,Declan Rice,Arsenal,M,41,28.082192,459,72,48.648649,891,687,...,61.111111,148,1054,743,1797,36,3,2327,8,2

In [21]:
arsenal["team_name"].value_counts()

team_name
Nottingham Forest             30
West Ham United               30
Aston Villa                   29
Sunderland                    28
Wolverhampton                 28
Crystal Palace                27
Manchester United             27
Brighton &amp; Hove Albion    27
Tottenham Hotspur             27
Manchester City               26
Burnley                       26
Bournemouth                   25
Newcastle United              25
Arsenal                       24
Chelsea                       24
Leeds United                  24
Fulham                        23
Brentford                     23
Liverpool                     22
Everton                       22
Name: count, dtype: int64

In [22]:
epl_team = epl.groupby("team_name").sum(numeric_only=True)
epl_team.head()

,accurateChippedPasses,accurateCrosses,accurateCrossesPercentage,accurateFinalThirdPasses,accurateLongBalls,accurateLongBallsPercentage,accurateOppositionHalfPasses,accurateOwnHalfPasses,accuratePasses,accuratePassesPercentage,...,totalLongBalls,totalOppositionHalfPasses,totalOwnHalfPasses,totalPasses,totalShots,totwAppearances,touches,wasFouled,yellowCards,yellowRedCards
team_name,,,,,,,,,,,,,,,,,,,,,
Arsenal,415,152,359.090550,3909,653,880.626272,7311,6461,13772,1955.358263,...,1578,9358,7029,16387,514,32,22856,371,45,0
Aston Villa,502,126,366.690186,3335,703,1250.801619,6497,7100,13597,2416.391784,...,1504,8192,7744,15936,436,22,22240,431,56,0
Bournemouth,455,122,312.003780,2877,678,803.817973,5754,5373,11127,1926.249198,...,1823,7915,6006,13921,438,13,20738,340,75,0
Brentford,510,173,448.157162,2289,829,1046.762525,4798,6210,11008,1881.999143,...,2028,6999,6888,13887,376,16,20656,317,63,0
Brighton &amp; Hove Albion,549,167,455.290174,3028,717,1126.818666,6094,7751,13845,2109.938141,...,1653,8112,8420,16532,449,17,23272,344,85,0

In [23]:
epl_team.loc["Arsenal"]

accurateChippedPasses          415.00000
accurateCrosses                152.00000
accurateCrossesPercentage      359.09055
accurateFinalThirdPasses      3909.00000
accurateLongBalls              653.00000
                                ...
totwAppearances                 32.00000
touches                      22856.00000
wasFouled                      371.00000
yellowCards                     45.00000
yellowRedCards                   0.00000
Name: Arsenal, Length: 103, dtype: float64

In [24]:
epl_team.sort_values("totalShots", ascending=False).head(5)

,accurateChippedPasses,accurateCrosses,accurateCrossesPercentage,accurateFinalThirdPasses,accurateLongBalls,accurateLongBallsPercentage,accurateOppositionHalfPasses,accurateOwnHalfPasses,accuratePasses,accuratePassesPercentage,...,totalLongBalls,totalOppositionHalfPasses,totalOwnHalfPasses,totalPasses,totalShots,totwAppearances,touches,wasFouled,yellowCards,yellowRedCards
team_name,,,,,,,,,,,,,,,,,,,,,
Manchester City,631,157,593.477936,5184,726,1223.048717,10652,8273,18925,2270.166532,...,1478,12491,8990,21481,584,41,28583,398,69,0
Manchester United,587,163,523.231579,3465,786,1121.345145,7034,6478,13512,2160.876400,...,1733,9087,7237,16324,545,21,23022,367,56,1
Liverpool FC,510,149,306.963849,4843,740,1007.634058,9212,6869,16081,1871.793896,...,1625,11200,7556,18756,541,28,25546,351,52,0
Arsenal,415,152,359.090550,3909,653,880.626272,7311,6461,13772,1955.358263,...,1578,9358,7029,16387,514,32,22856,371,45,0
Chelsea,489,137,508.311682,3808,731,1252.127296,7849,8837,16686,2317.860813,...,1589,9570,9526,19096,484,23,25584,397,77,3

In [25]:
epl_team.loc[["Arsenal", "Manchester City"]][["totalShots", "totalPasses", "touches", "wasFouled"]]

                 totalShots  totalPasses  touches  wasFouled
team_name
Arsenal                 514        16387    22856        371
Manchester City         584        21481    28583        398

In [26]:
epl_team[["totalShots", "totalPasses", "touches", "wasFouled"]].sort_values("totalShots", ascending=False)

                            totalShots  totalPasses  touches  wasFouled
team_name
Manchester City                    584        21481    28583        398
Manchester United                  545        16324    23022        367
Liverpool FC                       541        18756    25546        351
Arsenal                            514        16387    22856        371
Chelsea                            484        19096    25584        397
Newcastle United                   454        15592    22542        401
Brighton &amp; Hove Albion         449        16532    23272        344
Leeds United                       447        13992    20906        387
Bournemouth                        438        13921    20738        340
Aston Villa                        436        15936    22240        431
Fulham                             435        16616    23219        316
Nottingham Forest                  428        14007    20847        390
Crystal Palace                     405        12908    19589        324
Everton                            392        13391    20333        379
Tottenham Hotspur                  385        14217    21351        338
Brentford                          376        13887    20656        317
West Ham United                    367        12832    19687        358
Sunderland                         352        12957    19393        372
Burnley                            321        13654    20333        310
Wolverhampton                      317        12850    19625        366

In [27]:
epl_team.to_csv("epl_team.csv")